dna = "GCCGAGGGGGCGGTGCCCACACAACCATTTACTACCTCCCCTGAACGTAGATGACGAATCGCGCAGTGGGTTGCCTAGCCGGGGCTCATTACACACCCCTGTGAACGTGCAAACGGCCGGTGGGATTTACTGCGCTACAAAGGTGCGATTGCTCAATGCTGTTATCTCGCCCGCGAGGTGGCTGTGTAATGGAGTCCACATTCGACATCCTGGTGCACGCTTTTGACCACCGCCCGTTTGCATCCTCGCCCGGAGAGGTACAGTGGAGAGTCGATAGTCCCAAGTCCTCACCGTTCTGTGGAAAATGTGTCAGCCGAGTGCATTCGTTTTCAAGAAATTCGGTCTTCTTAATGGGGAGCATTTAACCGTTGTTGGGAGAGCACACCGGGGTATGGCTCAGGCTTCGCCTTCAGCCACTCTTGTTAAATCAGCGGTGGGACCGCGGATTGCTTATGTCCGATAGTAGTTGACGATTCTACGCATTTAAACCTCAAATTGTTCACAGAGAGCAGTTCACTAATGCTATGTAATTGCTCCACCCGAGGGCGTGTCCCAATTGCTAGACCAAGTAATAAACCCCCGGCTTGAATAAAAAACGCCGTAGTCATTGATCGAGCCTTCTCGGACGGAAATCGGAAACACCCTTGCCCTGACAGGGGCACCTTAGCTTCCCTTGCACAAATCACGGGGAGTAGCAAGATCGCATATCGATTCCGCTTAATCCCCCGACATGAAACGCACGGGGTCCTAGGAAGTGTAACGGATGATAGTCCAGAAAGACAAATTTGTTTAGGCGATTAAGTCCCGAGCAAACTGATAACCCAATCCGTCGTTGTAGACCGTATACGCAACGGGGGCGGTAGGTACAGATACGGTGTACAATGTGAGATTCGTGGGGCCCCAGGTGTAGATCCGGAAGATCATA"


a = 0
c = 0 
g = 0 
t = 0

nucleotides = [a, c, g, t]
for char in dna: 
    if char == 'A':
        a += 1
    if char == 'G':
        g += 1
    if char == 'C':
        c += 1
    if char == 'T':
        t += 1

return_str = ""
for nucleotide in nucleotides: 
    temp = str(nucleotide) + " "
    str.join(temp)

print(str)