
class Count_Nucleotides:
    def count_dna_nucleotides(self, dna_string):
        
        a = 0
        c = 0 
        g = 0 
        t = 0

        for char in dna_string: 
            if char == 'A':
                a += 1
            if char == 'G':
                g += 1
            if char == 'C':
                c += 1
            if char == 'T':
                t += 1

        return "{} {} {} {}".format(a, c, g , t)

dna_string = "GCCGAGGGGGCGGTGCCCACACAACCATTTACTACCTCCCCTGAACGTAGATGACGAATCGCGCAGTGGGTTGCCTAGCCGGGGCTCATTACACACCCCTGTGAACGTGCAAACGGCCGGTGGGATTTACTGCGCTACAAAGGTGCGATTGCTCAATGCTGTTATCTCGCCCGCGAGGTGGCTGTGTAATGGAGTCCACATTCGACATCCTGGTGCACGCTTTTGACCACCGCCCGTTTGCATCCTCGCCCGGAGAGGTACAGTGGAGAGTCGATAGTCCCAAGTCCTCACCGTTCTGTGGAAAATGTGTCAGCCGAGTGCATTCGTTTTCAAGAAATTCGGTCTTCTTAATGGGGAGCATTTAACCGTTGTTGGGAGAGCACACCGGGGTATGGCTCAGGCTTCGCCTTCAGCCACTCTTGTTAAATCAGCGGTGGGACCGCGGATTGCTTATGTCCGATAGTAGTTGACGATTCTACGCATTTAAACCTCAAATTGTTCACAGAGAGCAGTTCACTAATGCTATGTAATTGCTCCACCCGAGGGCGTGTCCCAATTGCTAGACCAAGTAATAAACCCCCGGCTTGAATAAAAAACGCCGTAGTCATTGATCGAGCCTTCTCGGACGGAAATCGGAAACACCCTTGCCCTGACAGGGGCACCTTAGCTTCCCTTGCACAAATCACGGGGAGTAGCAAGATCGCATATCGATTCCGCTTAATCCCCCGACATGAAACGCACGGGGTCCTAGGAAGTGTAACGGATGATAGTCCAGAAAGACAAATTTGTTTAGGCGATTAAGTCCCGAGCAAACTGATAACCCAATCCGTCGTTGTAGACCGTATACGCAACGGGGGCGGTAGGTACAGATACGGTGTACAATGTGAGATTCGTGGGGCCCCAGGTGTAGATCCGGAAGATCATA"
nucleotide_counter = Count_Nucleotides()
nucleotide_counter.count_dna_nucleotides(dna_string)
